# Generated by Django 3.2.13 on 2022-10-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='ND_Users',
        ),
    ]
