# Generated by Django 3.2.13 on 2022-10-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_rename_users_nd_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ND_Users',
            new_name='NDUsers',
        ),
    ]
