# Generated by Django 3.2.13 on 2022-10-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_rename_nd_users_ndusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NDUsers',
            new_name='People',
        ),
    ]
