# Generated by Django 3.2.13 on 2022-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_rename_ndusers_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
