# Generated by Django 3.2.13 on 2022-10-29 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_order_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropoff', models.CharField(max_length=200)),
                ('pickup', models.CharField(max_length=200)),
                ('tip', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)])),
                ('readyBy', models.TimeField()),
                ('delivererId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OldDeliverer', to='testing.person')),
                ('ordererId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OldOrderer', to='testing.person')),
            ],
        ),
    ]
